/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pspHelper;

import static pspHelper.DocumentGenerator.gen;

/**
 *
 * @author Hannah
 */
public class SourceProgramListing extends javax.swing.JPanel {

    /**
     * Creates new form SourceProgramListingX
     */
    public SourceProgramListing() {
        initComponents();
    }

    public void generate() {
        gen.addParagraph(code.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        code = new javax.swing.JTextArea();

        code.setColumns(20);
        code.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        code.setLineWrap(true);
        code.setRows(5);
        code.setText("#include <stdio.h>\n#include <math.h>\n\nint main() {\n\t\n\tint n, i = 0;\n\tdouble avg, sum = 0, upperSd = 0, sd;\n\tdouble inputArr[500];\n\t\n\tprintf(\"Please enter the number of inputs: \");\n\tscanf(\"%d\", &n);\n\t\n\tif(n > 0) {\n\t\tfor(i; i < n; i++) {\n\t\t\tprintf(\"\\nInput # %d: \", i+1);\n\t\t\tscanf(\"%lf\", &inputArr[i]);\n\t\t\tsum += inputArr[i];\n\t\t}\n\t\t\n\t\tavg = sum/n;\n\t\t\n\t\ti = 0;\n\t\tfor(i; i < n; i++)\n\t\t\tupperSd += pow((inputArr[i] - avg),2);\n\t\t\t\n\t\tsd = sqrt(upperSd/(n-1));\n\t\t\n\t\tprintf(\"\\n\\nAverage: %lf\", avg);\n\t\tprintf(\"\\nStandard Deviation: %lf\", sd);\n\t}\n\t\n\treturn 0;\n}\n");
        code.setOpaque(false);
        jScrollPane1.setViewportView(code);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea code;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
