/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pspHelper;

import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static pspHelper.DocumentGenerator.gen;

/**
 *
 * @author Hannah
 */
public class TimeRecordingLog extends javax.swing.JPanel {
    
    /**
     * Creates new form DefectRecordingLog
     */
    public TimeRecordingLog() {
        initComponents();
    }
    
    public void generate() {
        addDeltaTime();
        gen.addTable(table0);
    }
    
    public void addDeltaTime() {
        int rows = table0.getRowCount();

        for(int i = 0; i < rows; i++) {
            table0.setValueAt(getDeltaTime(i), i, 4);
        }
    }
    
    public String getDeltaTime(int row) {
        try {
            if(table0.getValueAt(row, 1) == "" || table0.getValueAt(row, 2) == "")
                return "";
            
            String time1 = (String) table0.getValueAt(row, 1);
            String time2 = (String) table0.getValueAt(row, 2);
            
            int interrupt = (int) table0.getValueAt(row, 3);
            
            SimpleDateFormat format = new SimpleDateFormat("HH:mm");
            Date date1 = format.parse(time1);
            Date date2 = format.parse(time2);
            long diff = date2.getTime() - date1.getTime();
            //long diffMinutes = diff / (60 * 1000) % 60;
            long diffMinutes = TimeUnit.MILLISECONDS.toMinutes(diff);
            System.out.println("date1: " + date1.getTime());
            System.out.println("date2: " + date2.getTime());
            System.out.println("diff in long: " + diff);
            System.out.println("DELTA TIME X: " + diffMinutes);
            diffMinutes -= interrupt;
            System.out.println("DELTA TIME Y: " + diffMinutes);
            return diffMinutes + "";
        } catch (ParseException ex) {
            Logger.getLogger(TimeRecordingLog.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }
    
    public JTable getTimeLog(){
        return table0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane0 = new javax.swing.JScrollPane();
        table0 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1057, 400));
        setPreferredSize(new java.awt.Dimension(1057, 400));

        pane0.setMinimumSize(new java.awt.Dimension(1057, 350));

        table0.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        table0.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8/13/16", "3:26", "4:26",  new Integer(30), null, "Plan", "CR Break"},
                {"8/13/16", "4:27", "5:27",  new Integer(0), null, "Design", "Nothen"}
            },
            new String [] {
                "Date", "Start", "Stop", "Interruption Time", "Delta Time", "Phase", "Comments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table0.setFocusable(false);
        table0.setGridColor(new java.awt.Color(204, 204, 204));
        table0.setMinimumSize(new java.awt.Dimension(1057, 350));
        table0.setOpaque(false);
        table0.setPreferredSize(new java.awt.Dimension(1057, 350));
        table0.setRowHeight(40);
        table0.setRowSelectionAllowed(false);
        table0.getTableHeader().setResizingAllowed(false);
        table0.getTableHeader().setReorderingAllowed(false);
        table0.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 18));
        pane0.setViewportView(table0);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD ROWS");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("* Use the 24 Hour Time Format (MM:SS)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(pane0, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) table0.getModel();
        dtm.addRow(new Object[] {"", "", "", "", "", ""});
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane pane0;
    private javax.swing.JTable table0;
    // End of variables declaration//GEN-END:variables
}
